### ISSUE TITLE
Instructions to authenticate prior to using 

### ISSUE THREAD

**Issue by dan-lutd** [appitekltd/aptk-graphsql#1]
`( async () => {
       const request = `{
            MyName: Account(limit:10) {
            Id
            Name
            Contact(limit:13) {
                FirstName
                LastName
            }
            Industry
            }
      }`

        const salesforceApiUrl = 'https://my.scratch.org.com/services/apexrest/aptk_graphql/graphql'
        const sfreseult = await axios.post(
            salesforceApiUrl,
            {
              query: request
            }
          )
        console.log(sfreseult.data)

    })().catch(ex => console.error(ex.stack)); `

I have my scratch org open in a browser.

running this returns the message:
`{ status: 401,
  statusText: 'Unauthorized',...`

I'm expecting a Salesforce Login or allow  Screen in my scratch org.

What am I missing? What forces a connection to Salesforce and creates the token? 
Is token creation the app's responsibility?

**Comment by aptkdev** [comment]
Hey man, thanks for reaching out, our support told me they've helped you out with this one!

For anyone else visiting this issue, GraphSQL does indeed expect you to provide an authenticated token as an 'Authorization' header - there is no built in login flow.

You can get a token yourself through a [Salesforce connected app](https://help.salesforce.com/articleView?id=connected_app_overview.htm&type=5), our own [Token Generator](https://www.appitek.com/tools/token-generator/), or going through the [Salesforce oAuth flow](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_oauth.htm).

I've updated the documentation in the app to make this clearer, and we now provide an example cURL passing the authorization token to get you started:
`curl ${INSTANCE_URL}/services/apexrest/aptk_graphql/graphql -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "X-PrettyPrint:1" -d "{ \"query\": \"query { Account(Limit: 2) { Name } }\" }" -s `

As you've said to support you've got yourself all set up now I'll go ahead and close this.
Cheers!

**Comment by dan-lutd** [comment]
As a followup for node.js  , I am using axios and the call looks like this:

     

        ( async () => {
          const request = `{
            MyName: Account(limit:10) {
            Id
            Name
            Contact(limit:13) {
                FirstName
                LastName
            }
            Industry
            }
            Lead(limit:5) {
            FirstName
            }
        }`

        const salesforceApiUrl = process.env.instanceUrl + '/services/apexrest/aptk_graphql/graphql'
        
        const headers = {
            headers: {
                "Authorization" : `Bearer ${process.env.accessToken} `
            }
        }

        const sfResult = await axios.post(
            salesforceApiUrl,
            {
              query: request
            },
            headers
          )
        console.log(sfResult.data)
        res.send(sfResult.data);

    })().catch(ex => console.error(ex.stack));
    `
Where `process.env.instanceUrl and process.env.accessToken` came from authenticating with jsforce with a Salesforce connected app,
